services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database

  webserver:
    build:
      context: ./
      dockerfile: webserver.dockerfile
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - database

  database:
    image: postgres:17-alpine3.20
    container_name: test-crud-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: test-crud-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  db_data:
