services:
  app:
    build:
      context: ./ 
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database
  
  webserver:
    build:
      context: ./ 
      dockerfile: webserver.dockerfile
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - database

  database:
    image: mysql:9.4
    container_name: test-crud-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql


  pma:
    image: phpmyadmin:5.2.2
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  db_data:
